# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "/eece570" # the subpath of your site, e.g. /blog
url: "https://xxlya.github.io/EECE-570/" # the base hostname & protocol for your site, e.g. http://example.com

number: EECE 570
title: Fundamentals of Visual Computing
semester: Spring 2023

# navigation:
#   - title: Overview
#     subfolderitems:
#       - page: Description
#         url: '#description'
#       - page: Course Description
#         url: '#description'
#       - page: Contacts
#         url: '#contact'
#       - page: Time and Location
#         url: '#time-and-location'
#       - page: Reading and Presentation
#         url: '#reading-and-presentation'
#       - page: Grading
#         url: '#grading'
#   - page: Schedule
#     url: '#schedule'
#   # - title: Commitments 
#   #   subfolderitems:
#   #     - page: Homework and Quizzes
#   #       url: '#hwqz'
#   #     - page: Labs
#   #       url: '#labs'
#   #     - page: Projects
#   #       url: '#projects'
#   #     - page: Exams
#   #       url: '#exams'
#   #     - page: Scale
#   #       url: '#scale'
#   - page: Commitments
#     url: '#commitments'

# instructors:
#   - id: yorgey
#     name: Dr. Brent Yorgey
#     email: yorgey@hendrix.edu
#     web: http://ozark.hendrix.edu/~yorgey
#     phone: (501) 450-1377
#     officehours: https://byorgey.youcanbook.me
#   - id: goadrich
#     name: Dr. Mark Goadrich
#     email: goadrich@hendrix.edu
#     web: http://mark.goadrich.com
#     phone: (501) 450-1367
#     officehours: http://mark.goadrich.com/schedule.html
#   - id: ferrer
#     name: Dr. Gabriel Ferrer
#     email: ferrer@hendrix.edu
#     web: http://ozark.hendrix.edu/~ferrer
#     phone: (501) 450-3879
#     officehours: https://drferrer.youcanbook.me/
#   - id: seme
#     name: Prof. Lars Seme
#     email: seme@hendrix.edu
#     web: https://www.hendrix.edu/mathcs/profile.aspx?id=70795
#     phone: (501) 450-1256
#     officehours: ???

# offerings:
#   - name: LECTURE 01
#     loc: MCREY 110
#     time: MWF 8:10am - 9:00am
#     instructor: xiaoxiao
#   - name: TA session 1
#     loc: TBA
#     time: TBA
#     instructor: Chun-Yin Huang
#   - name: LAB 01
#     loc: Snoddy Computer Lab
#     time: R 1:10pm - 4:00pm
#     instructor: ferrer
#   - name: LAB 02
#     loc: Snoddy Computer Lab
#     time: W 1:10pm - 4:00pm
#     instructor: seme

# resources:
#   - name: Python 3
#     image: assets/images/pythonlogo.png
#     url: http://python.org
#   - name: Azure Notebooks
#     image: assets/images/azure.png
#     url: https://notebooks.azure.com/
#   - name: Pycharm
#     image: assets/images/pycharmlogo.png
#     url: https://www.jetbrains.com/pycharm/

# extra-resources:
#   - name: "How to Think Like a Computer Scientist: Interactive Edition"
#     image: assets/images/runestone_logo.png
#     url: https://runestone.academy/runestone/books/published/thinkcspy/index.html
#   - name: Python Tutor
#     image: assets/images/python_tutor.png
#     url: http://pythontutor.com/
#   - name: CodingBat Python
#     image: assets/images/codingbat.jpg
#     url: https://codingbat.com/python
#   - name: CheckiO Python Practice
#     image: assets/images/checkio_logo_small.png
#     url: https://py.checkio.org/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
